#!/usr/bin/env python3 
import time
import signal
import os

if __name__ == "__main__":
    
    def signal_handler_suspend(*args):
        print("Suspended")

    def signal_handler_resume(*args):
        print("Continued")

    print(os.getpid())
    signal.signal(signal.SIGTSTP, signal_handler_suspend)
    signal.signal(signal.SIGCONT, signal_handler_resume)

    i=0
    while i<100:
        time.sleep(1)
        i+=1
        print(i)

